### ISSUE TITLE
Wrong examples in extra links documentation

### ISSUE THREAD

**Issue by Teeushii** [useblocks/sphinxcontrib-needs#125]
Hi,

The examples defined in the [extra links](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/need.html#extra-links) section are wrong, and lead to a building error, see following log:

```
# Python version: 3.7.4 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 236, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 395, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.7/site-packages/sphinx/registry.py", line 487, in load_extension
    metadata = setup(app)
  File "/usr/local/lib/python3.7/site-packages/sphinxcontrib/needs/needs.py", line 332, in setup
    if title_optional or title_from_content:
UnboundLocalError: local variable 'title_optional' referenced before assignment
```

The correct JSON property is 'option'  instead of 'name', as stated in the [needs_extra_links](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-extra-links) option documentation.

**Comment by danwos** [comment]
Thanks for reporting this.
Changed it already.
