### ISSUE TITLE
Build fails if conf.py contains tags.has()

### ISSUE THREAD

**Issue by bunder** [useblocks/sphinxcontrib-needs#142]
Found with sphinxcontrib-needs 0.5.3.

If I use `tags.has()` in `conf.py` according to [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html#conf-tags), build fails with

```
WARNING: while setting up extension sphinxcontrib.needs: Error during sphinxcontrib-needs setup: /home/aleontiev/projects/mcom03/doc/doc/conf.py, name 'tags' is not defined

Exception occurred:
  File "/home/aleontiev/.local/share/virtualenvs/doc-oBoy3zpN/src/sphinxcontrib-needs/sphinxcontrib/needs/needs.py", line 195, in setup
    NeedDirective.option_spec.update(extra_options)
UnboundLocalError: local variable 'extra_options' referenced before assignment
The full traceback has been saved in /tmp/sphinx-err-jjhd2fys.log, if you want to report the issue to the developers.
```

```
# Sphinx version: 2.4.3
# Python version: 3.6.8 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/aleontiev/.local/share/virtualenvs/doc-oBoy3zpN/lib/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/aleontiev/.local/share/virtualenvs/doc-oBoy3zpN/lib/python3.6/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/home/aleontiev/.local/share/virtualenvs/doc-oBoy3zpN/lib/python3.6/site-packages/sphinx/application.py", line 397, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/aleontiev/.local/share/virtualenvs/doc-oBoy3zpN/lib/python3.6/site-packages/sphinx/registry.py", line 465, in load_extension
    metadata = setup(app)
  File "/home/aleontiev/.local/share/virtualenvs/doc-oBoy3zpN/src/sphinxcontrib-needs/sphinxcontrib/needs/needs.py", line 195, in setup
    NeedDirective.option_spec.update(extra_options)
UnboundLocalError: local variable 'extra_options' referenced before assignment```

**Comment by danwos** [comment]
Thanks for reporting and sorry for the delay.
The problem was based on an internal import of ``conf.py``, which needed to be removed and handled differently to get rid of it.
Release will need some days, as I'm working on some features which shall get part of it.
