### ISSUE TITLE
Error encountered when trying to use the `add_need` API

### ISSUE THREAD

**Issue by lassebn** [useblocks/sphinxcontrib-needs#148]
I'm trying to add my own directive from which I'd like to add new needs.

As a small basic step to get me started I've added the following to add a single hardcoded need

```python
add_need(
  app=self.app,
  state=self.state,
  docname=self.state.document.settings.env.docname,
  lineno=self.lineno,
  need_type='testcase',
  title='Title of the unit test',
  content='content',
  id='HULLU-1'
)
```

But I get the following error when I'm building the documentation

```
# Sphinx version: 2.4.2
# Python version: 3.7.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.0a1
# Last messages:
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  6%] all-needs
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.2) from /usr/local/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib_applehelp-1.0.2-py3.7.egg/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib_devhelp-1.0.2-py3.7.egg/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /usr/local/lib/python3.7/site-packages/sphinxcontrib_htmlhelp-1.0.3-py3.7.egg/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /usr/local/lib/python3.7/site-packages/sphinxcontrib_serializinghtml-1.1.4-py3.7.egg/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.7/site-packages/sphinxcontrib_qthelp-1.0.3-py3.7.egg/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.7/site-packages/alabaster-0.7.12-py3.7.egg/alabaster/__init__.py
#   sphinxcontrib.needs (0.5.6) from /usr/local/lib/python3.7/site-packages/sphinxcontrib_needs-0.5.6-py3.7.egg/sphinxcontrib/needs/__init__.py
#   sphinx.ext.todo (2.4.2) from /usr/local/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx_rtd_theme (unknown version) from /usr/local/lib/python3.7/site-packages/sphinx_rtd_theme/__init__.py
#   sphinxcontrib.test_reports (0.3.3) from /usr/local/lib/python3.7/site-packages/sphinx_test_reports-0.3.3-py3.7.egg/sphinxcontrib/test_reports/__init__.py
#   sphinx.ext.graphviz (2.4.2) from /usr/local/lib/python3.7/site-packages/sphinx/ext/graphviz.py
#   sphinxcontrib.plantuml (unknown version) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/plantuml.py
#   sphinxcontrib.images (2.4.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/images.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 542, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 537, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/usr/local/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 588, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/usr/local/lib/python3.7/site-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/usr/local/lib/python3.7/site-packages/sphinxcontrib_needs-0.5.6-py3.7.egg/sphinxcontrib/needs/directives/needlist.py", line 113, in process_needlist
    ref['refuri'] += '#' + need_info['target_node']['refid']
  File "/usr/local/lib/python3.7/site-packages/docutils-0.16-py3.7.egg/docutils/nodes.py", line 625, in __getitem__
    return self.attributes[key]
KeyError: 'refid'
```

Am I doing something obviously wrong?

**Comment by lassebn** [comment]
To add some more context, I've added a custom directive in `source/_extensions` with the following code

```python3
from docutils import nodes
from sphinxcontrib.needs.api import add_need
from sphinx.util.docutils import SphinxDirective

class TestCoverage(nodes.General, nodes.Element):
    pass

class TestCoverageDirective(SphinxDirective):

    has_content = True

    def run(self):
        add_need(
            app=self.env.app,
            state=self.state,
            docname=self.state.document.settings.env.docname,
            lineno=self.lineno,
            need_type='testcase',
            title='Title of the unit test',
            content='content',
            id='HULLU-1'
        )
        return []


def setup(app):
    app.add_directive("test-coverage", TestCoverageDirective)

    return {
        'version': '0.1',
    }

```

I'm using the following versions

* `sphinx`: 2.4.2
* `sphinxcontrib-needs`: 0.5.6
* `sphinx-test-reports`: 0.3.3

**Comment by lassebn** [comment]
### Success in my minimum example 🥇 
Ok, I was doing something stupid 😅  If my change my code to return the result of `add_need` like this

```python3
from docutils import nodes
from sphinxcontrib.needs.api import add_need
from sphinx.util.docutils import SphinxDirective

class TestCoverage(nodes.General, nodes.Element):
    pass

class TestCoverageDirective(SphinxDirective):

    has_content = True

    def run(self):
        need = add_need(
            app=self.env.app,
            state=self.state,
            docname=self.state.document.settings.env.docname,
            lineno=self.lineno,
            need_type='testcase',
            title='Title of the unit test',
            content='content',
            id='HULLU-1'
        )
        return need


def setup(app):
    app.add_directive("test-coverage", TestCoverageDirective)

    return {
        'version': '0.1',
    }
```

Then I'll get my need rendered.

### Failure in what I'd actually like to achive 😕 
What I'd actually like to do is create multiple needs from my single directive. From what I can read [here](https://www.sphinx-doc.org/en/master/extdev/markupapi.html) the `run` method of the directive must

>  return a list of Docutils/Sphinx nodes

If my modify my code to return `[need]` then I get the following error:

```
Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2157, in run_directive
    % (type_name, i, result[i]))
AssertionError: Directive "test-coverage" returned non-Node object (index 0): [<target: >, <Need: <paragraph...>>]
```

If I return `[need[0], need[1]]` it works. Any ideas? 🤔 

Thank you for any input 🙌

**Comment by lassebn** [comment]
Ah ok, I've realized my mistake. `add_need` already returns a list of Sphinx nodes, so the solution is to have the following if I'd like to create multiple needs.

```python3
result = []
result += add_need(...)
result += add_need(..)
return result
```
