### ISSUE TITLE
Build with needs_external_needs is unstable

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinxcontrib-needs#341]
On some builds (usually the 2nd build), Sphinx-needs aborts with this error:

```
Traceback (most recent call last):
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 402, in read
    self.events.emit('env-before-read-docs', self.env, docnames)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinxcontrib/needs/external_needs.py", line 66, in load_external_needs
    add_external_need(app, **need_params)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinxcontrib/needs/api/need.py", line 445, in add_external_need
    return add_need(app=app, **kwargs)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinxcontrib/needs/api/need.py", line 226, in add_need
    "This is not allowed. Document {}[{}] Title: {}.".format(need_id, docname, lineno, title)
sphinxcontrib.needs.api.exceptions.NeedsDuplicatedId: A need with ID REQ_001 already exists! This is not allowed. Document None[None] Title: Test requirement

Sphinx error:
A need with ID REQ_001 already exists! This is not allowed. Document None[None] Title: Test requirement
```

Another call of `sphinx-build -b html` finishes successfully.

**Comment by danwos** [comment]
Ohh,  strange behavior.
Looks like we have some problem with caching.

Does it also happen on the 3rd run?
If not, maybe sphinx detects the broken 2nd build and makes a full build for the next run and the game starts from the beginning.

But I already have an idea, as you wrote it happens when using external_needs.
The feature "external_needs" stores the imported needs in the common needs dictionary. So they behave like a local one, but only have 2-3 different attributes.
This overall needs_dict gets cached by sphinx.
On the next build, external_needs wants to import the needs again, but they are already in the cached needs_dict.
Therefore the error about an already existing need.

### Bug fix
If "external_needs" imports a need, check if it already exists.
If this is the case, check if the external related attributes are set (like is_external, external_source, ...).
If this indicates that the newly imported need is the same or an update of the already imported one (same source, is external, ...) update need_dict and don't throw an error about id duplication.

### Temporary workaround.
I'm sorry but the only solution I see is to force a full build ``sphinx-build -a -E -b html _build/html .``
