### ISSUE TITLE
Include directive causes NeedsDuplicatedId

### ISSUE THREAD

**Issue by elnino1** [useblocks/sphinxcontrib-needs#386]
I have a file in which I want to include some needs files. When using the include directive, it raises sphinxcontrib.needs.api.exceptions.NeedsDuplicatedId however there is no duplicate of Id.

**index.rst**

Feature X
======

blah blah

.. include:: req_B_001.rst

**req_B_001.rst**

.. req:: A requirement
   :id: REQ_B_001

    Requirement description

**sphinx-build**

...
reading sources... [ 36%] 2_engineering_requirements/2_requirements/feature_B/index
reading sources... [ 45%] 2_engineering_requirements/2_requirements/feature_B/req_B_001

```
Traceback (most recent call last):
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\application.py", line 337, in build
    self.builder.build_all()
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\builders\__init__.py", line 257, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\builders\__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\builders\__init__.py", line 414, in read
    self._read_serial(docnames)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\builders\__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\builders\__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\io.py", line 189, in read_doc
    pub.publish()
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\io.py", line 109, in read
    self.parse()
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinx\parsers.py", line 101, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\parsers\rst\states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\parsers\rst\states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\parsers\rst\states.py", line 2096, in directive
    return self.run_directive(
  File "c:\users\xxx\myapp\development\python\lib\site-packages\docutils\parsers\rst\states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinxcontrib\needs\directives\need.py", line 87, in run
    need_nodes = add_need(
  File "c:\users\xxx\myapp\development\python\lib\site-packages\sphinxcontrib\needs\api\need.py", line 225, in add_need
    raise NeedsDuplicatedId(
sphinxcontrib.needs.api.exceptions.NeedsDuplicatedId: A need with ID REQ_B_001 already exists! This is not allowed. Document 2_engineering_requirements/2_requirements/feature_B/req_B_001[1] Title: A requirement.
```

I understand that the include "copy/pastes" the content into index.rst file and then the req_B_001.rst file is parsed, causing the issue.

Changing the included file extension to txt avoid the duplication but is not acceptable in my case as I want to benefit of preview feature in Vscode plugin for rst extension. 

Do you know another workaround I could use ?

Don't you think it sounds like a bug ?

Thanks

**Comment by elnino1** [comment]
Many thanks, it does the trick.
Although this implies some writing rules to enforce on projects I guess it is acceptable for stakeholders.

Sorry for the duplicate and congratulations for the awesome response time.
