### ISSUE TITLE
Fix external_needs to load from URL

### ISSUE THREAD

**Issue by elnino1** [useblocks/sphinxcontrib-needs#459]
I think there is an error in line
https://github.com/useblocks/sphinxcontrib-needs/blob/master/sphinxcontrib/needs/external_needs.py#L36

This should be 
`response = s.get(source["json_url"])`

Else we have an error on next line while calling json() on response.

**Comment by danwos** [comment]
Thanks for the report and the hint with a solution. :+1: 

As you already know the solution, would it be okay for you to create also a PR?
Would speed up the integration of this fix a lot, as I have too much stuff to do currently. 
Thanks.

**Comment by David-Le-Nir** [comment]
Hello,

i'd like to create the PR but when I try to push the branch I get a
Permission to useblocks/sphinxcontrib-needs.git denied to David-Le-Nir

Note that as I am doing this for work, I changed my account but I'm the same "elnino1. ^^

**Comment by danwos** [comment]
You need to create a fork of sphinx-needs first, so copy of it under your own account.
E.g. https://github.com/David-Le-Nir/sphinxcontrib-needs. 

Then you can create a PR from your repo to sphinx-needs.

Creating Feature branches on https://github.com/useblocks/sphinxcontrib-needs is not allowed.

And already thanks for the PR :+1:

**Comment by David-Le-Nir** [comment]
Thank you.

I created the PR https://github.com/useblocks/sphinxcontrib-needs/pull/460

I didn't make create any test as I don't know how do you prefer to mock the http call to the json file.

This ticket and the 458 show that getting json from URL is not covered by test. 
That could be an opportunity to do it now. 
I would suggest requests-mock or mockito because I'm pretty new to python and I only played with those ones but I'm opened to any suggestion.

**Comment by danwos** [comment]
Yes you are right, we only have tests for ``json_path`` but not for ``json_url``.

requests-mock looks promising and easy to use.
I see no problem to use it.

Would it be okay for you to create the ``json_url`` test as well?
You could keep it simple and just add some lines to https://github.com/useblocks/sphinxcontrib-needs/blob/master/tests/test_needs_external_needs_build.py and update the related sphinx-project.

If you have any questions, I would be happy to support.

And thanks to your commitment.

**Comment by David-Le-Nir** [comment]
Hey, I added a simple test but unfortunately I'm not able to run tests locally (make test).
So I pushed, hoping the CI will execute them correctly. Small chance it will work on first try, but we will see ^^

**Comment by danwos** [comment]
Do you need any help to get "make test" working on your machine?
Maybe a ``poetry install`` helps, so that also all dev dependencies are installed.

I'm interested in this problem, as it may be also a problem on our side (wrong make setup, forgotten deps, ...)

**Comment by David-Le-Nir** [comment]
It seems I have all required dependencies. The error message while executing _make test_ is quite obscur and I cannot figure out what to check.

```
❯ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: sphinxcontrib-needs (0.7.5)
❯ make test
poetry run nosetests -v -w tests
Traceback (most recent call last):
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/loader.py", line 191, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/Users/david.lenir.e/Library/Caches/pypoetry/virtualenvs/sphinxcontrib-needs-yHp7n0lK-py3.10/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
make: *** [test] Error 1
```

**Comment by danwos** [comment]
Looks like a Problem with Python 3.10 and some Libs, which are not ready to support it.
Especially nosetests seems to have problems.

Any change to downgrade Python to 3.9 on your side?

This is really bad for us and I'm not sure when things will get fixed in the libs for Python 3.10.

Thanks for the log, it helped a lot :+1:

**Comment by David-Le-Nir** [comment]
I'm in 3.9.7

```
❯ python3 --version
Python 3.9.7
```

Or do you mean poetry/make are using a 3.10 version under the hood ?

**Comment by danwos** [comment]
Yes, it looks like this.
Found this line in your log: ``"/usr/local/Cellar/python@3.10/3.10.1``

**Comment by danwos** [comment]
But you could also start the tests "manually" in your venv of Python3.9 by just execute ``nosetests -v -w tests``.
This is the command from the Makefile, without calling poetry before.

**Comment by David-Le-Nir** [comment]
What I did
```
poetry env use /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
poetry  install
```
Then it performs better but I get an error about plantuml extension.

`ModuleNotFoundError: No module named 'sphinxcontrib.plantuml'`

This seems not installed by poetry ?

I'll try to run without poetry to use the exetension and the executable already present on my machine.

**Comment by danwos** [comment]
Ahh yes ,``sphinxcontrib.plantuml`` is an optional dependency for the user and must be installed by hand.

But for sure it is needed for our tests, as the tests also include the full sphinx-needs documentations.

You can do a ``pip install -r docs/requirements.txt`` to get all this deps. This is also happening on the CI, but not yet in the Makefile commands

**Comment by David-Le-Nir** [comment]
This is going better.
The requests_mock stuff is working well.
However I still have a test failure locally but this seems related to images and maybe due to my local setup.

**Comment by danwos** [comment]
Fixed by https://github.com/useblocks/sphinxcontrib-needs/pull/460

**Comment by ubmax** [comment]
Hey @David-Le-Nir, we'd love to reconnect regarding your use of Sphinx-Needs and hear your feedback. It would be awesome if you could reach out to us at info@useblocks.com. Looking forward to your thoughts!
