### ISSUE TITLE
sphinx-needs crashes after introduction of new artifact

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinxcontrib-needs#503]
Hi,

we have a situation where the sphinx-needs build (needs builder) crashes after switching from one branch to another.

This switch may, or may not, include addition of the following link type:

```py
needs_extra_links = [
    {
        "option": "parent_artifact",
        "incoming": "is parent artifact of",
        "outgoing": "has parent artifact",
    },
]
```

the output always looks like this, an unhandled KeyError:

```
preparing documents... done
writing output... [  1%] PackageReadme

Traceback (most recent call last):
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinxcontrib/needs/directives/need.py", line 285, in process_need_nodes
    create_back_links(env, links["option"])
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinxcontrib/needs/directives/need.py", line 350, in create_back_links
    if env.needs_workflow[f"backlink_creation_{option}"]:
KeyError: 'backlink_creation_parent_artifact'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 532, in write
    self._write_serial(sorted(docnames))
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 539, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 535, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 586, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/home/arwedus/project/.sphinx-venv/lib/python3.8/site-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_need_nodes at 0x7f64dbbe28b0> for event 'doctree-resolved' threw an exception (exception: 'backlink_creation_parent_artifact')

Extension error (sphinxcontrib.needs.directives.need):
Handler <function process_need_nodes at 0x7f64dbbe28b0> for event 'doctree-resolved' threw an exception (exception: 'backlink_creation_parent_artifact')
```

tested sphinx-needs version:

- current master (above)
- 0.7.5 has a similar issue

Other version info:
- sphinx v. 4.3 and v 4.4
- Python 3.8.9
- Ubuntu 18.04 and 20.04

I can't exactly reproduce the error, but it seems to be gone with a 2nd build, or if the build directory was empty.

**Comment by danwos** [comment]
I think the build after the checkout may reuse the saved sphinx env data, which was created based on the first branch.

So Sphinx tries to do an incremental build with inconsistent data.

If a build crashes, the following build always a full build.
So I think after a checkout a 'make clean' is needed.

**Comment by arwedus** [comment]
I should have mentioned how I call sphinx-build:

`sphinx-build -M html .. ../../build -c . -T -E -w ../../logs/sphinx_build_html_warnings.log -j auto`

I thought the "-E" option does read all files anew, which I thought would be enough.

**Comment by danwos** [comment]
You are right, "-E" should be enough.
But I have currently no other idea, what's happening, as the one above.

**Comment by arwedus** [comment]
your assumption is correct: when I re-run the build, it passes. When I delete the contents of the build tree, it passes. The `-E` option does not seem to have a similar cleansing effect.

**Comment by danwos** [comment]
I close this issue, as there is nothing we can do on Sphinx-Needs side.
Workaround is clear and maybe it's a bug in Sphinx, related to the "-E" option.
