### ISSUE TITLE
IDE: IDE cannot find needs.json if HTML builder is used

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#603]
With Sphinx-Needs 1.0.1, the IDE does not find the `needs.json`, if HTML builder is used, as it always looks for the json under
`<build_dir>/needs/needs.json`

With HTML builder, this is under `<build_dir>/html/needs.json`
> Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pygls/protocol.py", line 331, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/usr/local/lib/python3.10/site-packages/pygls/protocol.py", line 260, in _execute_request
    method_name, method_type, msg_id, handler(params))
  File "/home/dockeruser/.local/lib/python3.10/site-packages/esbonio/lsp/__init__.py", line 216, in on_hover
    hover_value = feature.hover(context)
  File "/usr/local/lib/python3.10/site-packages/sphinx_needs/lsp/esbonio.py", line 86, in hover
    self.needs_store.load_needs(needs_json)
  File "/usr/local/lib/python3.10/site-packages/sphinx_needs/lsp/needs_store.py", line 89, in load_needs
    raise FileNotFoundError(f"JSON file not found: {json_file}")
FileNotFoundError: JSON file not found: /workspaces/sphinx-needs-basics/docs/_build/needs/needs.json

**Comment by twodrops** [comment]
With Sphinx-Needs 1.0.1, the `needs.json` seems never to be created in a needs folder even when `-b html` is used. I find this good as this helps reuse the doctree cache from other builds. IDE however seems to be looking in a `/needs/needs.json` also with `-b html`
